### ISSUE TITLE
linux-headers-5.16.17-sun50iw6

### ISSUE THREAD

**Issue by vantyaevserega** [stas2z/orange-pi-images#1]
Hello, can you help me with headers for [Orangepi3-lts_3.0.8_debian_bullseye_server_linux5.16.17.img.xz](https://github.com/stas2z/orange-pi-images/releases/download/v0.1/Orangepi3-lts_3.0.8_debian_bullseye_server_linux5.16.17.img.xz)
?

I cannot find it(

**Comment by stas2z** [comment]
https://mega.nz/file/SVIkiBgZ#tRGnIhWp9IEBWZWoB22osVPTOlal_dzIzGj1WM8d3sg
its for zero2 but headers should be the same for the same kernel (images build same day)

also ill upload headers for 3lts soon, but it will be a bit newer kernel (but same version shown)

**Comment by vantyaevserega** [comment]
Thanks a lot
